# Generated by Django 5.2.16 on 2026-07-24 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_dept_ea719a_idx',
            old_name='students_st_dept_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_class_d5ce94_idx',
            old_name='students_st_class_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_year_259ed9_idx',
            old_name='students_st_year_idx',
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.PositiveSmallIntegerField(default=0, help_text='Overall attendance percentage (0-100).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(db_column='class', help_text="Class / section code, e.g. 'CO5I'", max_length=32),
        ),
    ]
