# Generated by Django 5.2.16 on 2026-07-24 05:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(help_text='e.g. 22516', max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Project', 'Project'), ('Elective', 'Elective')], default='Theory', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='department_code', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='departments.department', to_field='code')),
            ],
            options={
                'ordering': ['semester', 'code'],
                'indexes': [models.Index(fields=['department'], name='subjects_su_departm_266dcd_idx'), models.Index(fields=['semester'], name='subjects_su_semeste_0f3eff_idx')],
            },
        ),
    ]
