# Generated by Django 5.2.16 on 2026-07-24 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('General', 'General'), ('Exam', 'Exam'), ('Event', 'Event'), ('Holiday', 'Holiday'), ('Academic', 'Academic'), ('Urgent', 'Urgent')], default='General', max_length=16)),
                ('audience', models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('faculty', 'Faculty'), ('department', 'Department')], default='all', max_length=16)),
                ('pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_column='department_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='departments.department', to_field='code')),
            ],
            options={
                'ordering': ['-pinned', '-published_at'],
                'indexes': [models.Index(fields=['category'], name='notices_not_categor_30f710_idx'), models.Index(fields=['audience'], name='notices_not_audienc_def41a_idx')],
            },
        ),
    ]
