# Generated by Django 5.2.16 on 2026-07-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(db_column='class', help_text="Class / section, e.g. 'CO5I'", max_length=32)),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=32)),
                ('label', models.CharField(blank=True, help_text="Override label for breaks / labs, e.g. 'Recess'", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='faculty.faculty')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='subjects.subject')),
            ],
            options={
                'ordering': ['class_code', 'day', 'start_time'],
                'indexes': [models.Index(fields=['class_code', 'day'], name='timetable_t_class_4f9467_idx')],
                'unique_together': {('class_code', 'day', 'start_time')},
            },
        ),
    ]
