# Generated by Django 5.2.16 on 2026-07-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalManual',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Review', 'Review'), ('Published', 'Published')], default='Draft', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='practical_manuals/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='department_code', on_delete=django.db.models.deletion.PROTECT, related_name='manuals', to='departments.department', to_field='code')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manuals', to='subjects.subject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
