# Generated by Django 5.2.16 on 2026-07-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('departments', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='department',
            field=models.ForeignKey(db_column='department_code', on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='departments.department', to_field='code'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_classes', to='faculty.faculty'),
        ),
    ]
